// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYfALBZgdYGAshp-abycjlX_rop6qijc',
    appId: '1:757357545700:web:9a2f5aadc7ce35cb1e04f1',
    messagingSenderId: '757357545700',
    projectId: 'wallpaper-fbf2d',
    authDomain: 'wallpaper-fbf2d.firebaseapp.com',
    storageBucket: 'wallpaper-fbf2d.appspot.com',
    measurementId: 'G-VEDKQY3H63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo3Vcs3bSCKeElT9yEJoco3f8Eh0s99V4',
    appId: '1:757357545700:android:0bf50546f75debe31e04f1',
    messagingSenderId: '757357545700',
    projectId: 'wallpaper-fbf2d',
    storageBucket: 'wallpaper-fbf2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsU6nBQykETe6ur1cIsCk35lr4IlrNlaA',
    appId: '1:757357545700:ios:36de035e17b614d71e04f1',
    messagingSenderId: '757357545700',
    projectId: 'wallpaper-fbf2d',
    storageBucket: 'wallpaper-fbf2d.appspot.com',
    iosBundleId: 'com.example.wwalperApp',
  );

}